services:
  postgres:
    image: postgres:latest
    container_name: stage-gate-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stage-gate
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: stage-gate-redis
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog:latest
    container_name: stage-gate-mailhog
    ports:
      - '8025:8025'

  minio:
    image: minio/minio:latest
    container_name: stage-gate-minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
